// Code generated by protoc-gen-go. DO NOT EDIT.
// source: judge/judgepb/judge.proto

package judgepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewGameInfo_GamePattern int32

const (
	NewGameInfo_CHARMWOLF_GUARD    NewGameInfo_GamePattern = 0
	NewGameInfo_BLACKMARKETER_BROS NewGameInfo_GamePattern = 1
	NewGameInfo_BLOOD_WITCHER      NewGameInfo_GamePattern = 2
	NewGameInfo_CUPID_ROBBER       NewGameInfo_GamePattern = 3
	NewGameInfo_NIGHTMARE_GUARD    NewGameInfo_GamePattern = 4
	NewGameInfo_SHADOW_AVENGER     NewGameInfo_GamePattern = 5
	NewGameInfo_SWHI               NewGameInfo_GamePattern = 6
	NewGameInfo_SWGHI3             NewGameInfo_GamePattern = 7
)

var NewGameInfo_GamePattern_name = map[int32]string{
	0: "CHARMWOLF_GUARD",
	1: "BLACKMARKETER_BROS",
	2: "BLOOD_WITCHER",
	3: "CUPID_ROBBER",
	4: "NIGHTMARE_GUARD",
	5: "SHADOW_AVENGER",
	6: "SWHI",
	7: "SWGHI3",
}

var NewGameInfo_GamePattern_value = map[string]int32{
	"CHARMWOLF_GUARD":    0,
	"BLACKMARKETER_BROS": 1,
	"BLOOD_WITCHER":      2,
	"CUPID_ROBBER":       3,
	"NIGHTMARE_GUARD":    4,
	"SHADOW_AVENGER":     5,
	"SWHI":               6,
	"SWGHI3":             7,
}

func (x NewGameInfo_GamePattern) String() string {
	return proto.EnumName(NewGameInfo_GamePattern_name, int32(x))
}

func (NewGameInfo_GamePattern) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d265219a8a7b46e8, []int{0, 0}
}

type NewGameInfo struct {
	PlayerAmount         int32                   `protobuf:"varint,1,opt,name=playerAmount,proto3" json:"playerAmount,omitempty"`
	GamePattern          NewGameInfo_GamePattern `protobuf:"varint,2,opt,name=gamePattern,proto3,enum=judge.NewGameInfo_GamePattern" json:"gamePattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *NewGameInfo) Reset()         { *m = NewGameInfo{} }
func (m *NewGameInfo) String() string { return proto.CompactTextString(m) }
func (*NewGameInfo) ProtoMessage()    {}
func (*NewGameInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d265219a8a7b46e8, []int{0}
}

func (m *NewGameInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewGameInfo.Unmarshal(m, b)
}
func (m *NewGameInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewGameInfo.Marshal(b, m, deterministic)
}
func (m *NewGameInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewGameInfo.Merge(m, src)
}
func (m *NewGameInfo) XXX_Size() int {
	return xxx_messageInfo_NewGameInfo.Size(m)
}
func (m *NewGameInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NewGameInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NewGameInfo proto.InternalMessageInfo

func (m *NewGameInfo) GetPlayerAmount() int32 {
	if m != nil {
		return m.PlayerAmount
	}
	return 0
}

func (m *NewGameInfo) GetGamePattern() NewGameInfo_GamePattern {
	if m != nil {
		return m.GamePattern
	}
	return NewGameInfo_CHARMWOLF_GUARD
}

type StartGameRequest struct {
	NewGameInfo          *NewGameInfo `protobuf:"bytes,1,opt,name=new_game_info,json=newGameInfo,proto3" json:"new_game_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *StartGameRequest) Reset()         { *m = StartGameRequest{} }
func (m *StartGameRequest) String() string { return proto.CompactTextString(m) }
func (*StartGameRequest) ProtoMessage()    {}
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d265219a8a7b46e8, []int{1}
}

func (m *StartGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartGameRequest.Unmarshal(m, b)
}
func (m *StartGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartGameRequest.Marshal(b, m, deterministic)
}
func (m *StartGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartGameRequest.Merge(m, src)
}
func (m *StartGameRequest) XXX_Size() int {
	return xxx_messageInfo_StartGameRequest.Size(m)
}
func (m *StartGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartGameRequest proto.InternalMessageInfo

func (m *StartGameRequest) GetNewGameInfo() *NewGameInfo {
	if m != nil {
		return m.NewGameInfo
	}
	return nil
}

type StartGameResponse struct {
	ResponseStartgame    string   `protobuf:"bytes,1,opt,name=response_startgame,json=responseStartgame,proto3" json:"response_startgame,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartGameResponse) Reset()         { *m = StartGameResponse{} }
func (m *StartGameResponse) String() string { return proto.CompactTextString(m) }
func (*StartGameResponse) ProtoMessage()    {}
func (*StartGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d265219a8a7b46e8, []int{2}
}

func (m *StartGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartGameResponse.Unmarshal(m, b)
}
func (m *StartGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartGameResponse.Marshal(b, m, deterministic)
}
func (m *StartGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartGameResponse.Merge(m, src)
}
func (m *StartGameResponse) XXX_Size() int {
	return xxx_messageInfo_StartGameResponse.Size(m)
}
func (m *StartGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartGameResponse proto.InternalMessageInfo

func (m *StartGameResponse) GetResponseStartgame() string {
	if m != nil {
		return m.ResponseStartgame
	}
	return ""
}

func init() {
	proto.RegisterEnum("judge.NewGameInfo_GamePattern", NewGameInfo_GamePattern_name, NewGameInfo_GamePattern_value)
	proto.RegisterType((*NewGameInfo)(nil), "judge.NewGameInfo")
	proto.RegisterType((*StartGameRequest)(nil), "judge.StartGameRequest")
	proto.RegisterType((*StartGameResponse)(nil), "judge.StartGameResponse")
}

func init() { proto.RegisterFile("judge/judgepb/judge.proto", fileDescriptor_d265219a8a7b46e8) }

var fileDescriptor_d265219a8a7b46e8 = []byte{
	// 377 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0x4b, 0x8f, 0xda, 0x30,
	0x14, 0x85, 0x09, 0xe5, 0x51, 0x6e, 0x80, 0x9a, 0x5b, 0xa9, 0xa5, 0x5d, 0x54, 0x28, 0x2b, 0x36,
	0xa5, 0x12, 0x48, 0x5d, 0xd7, 0x79, 0x34, 0x49, 0x79, 0x04, 0x39, 0xd0, 0x48, 0xdd, 0x58, 0xa1,
	0x35, 0x88, 0xaa, 0x24, 0x69, 0x12, 0x06, 0xcd, 0xff, 0x98, 0xf5, 0xfc, 0xd6, 0x51, 0x42, 0x10,
	0x99, 0x61, 0x63, 0xfb, 0xf8, 0xd8, 0x9f, 0xcf, 0xb5, 0x2e, 0x7c, 0xf8, 0x7b, 0xfc, 0xb3, 0x13,
	0x5f, 0xf2, 0x31, 0xda, 0x9c, 0xe7, 0x51, 0x14, 0x87, 0x69, 0x88, 0xf5, 0x5c, 0x28, 0x0f, 0x55,
	0x90, 0x17, 0xe2, 0x64, 0xfa, 0x07, 0x61, 0x07, 0xdb, 0x10, 0x15, 0x68, 0x47, 0xff, 0xfc, 0x7b,
	0x11, 0xd3, 0x43, 0x78, 0x0c, 0xd2, 0xbe, 0x34, 0x90, 0x86, 0x75, 0xf6, 0x6c, 0x0f, 0xbf, 0x81,
	0xbc, 0xf3, 0x0f, 0x62, 0xe9, 0xa7, 0xa9, 0x88, 0x83, 0x7e, 0x75, 0x20, 0x0d, 0xbb, 0xe3, 0x4f,
	0xa3, 0x33, 0xbd, 0x04, 0x1b, 0x99, 0xd7, 0x53, 0xac, 0x7c, 0x45, 0x79, 0x94, 0x40, 0x2e, 0x99,
	0xf8, 0x16, 0xde, 0x68, 0x16, 0x65, 0x73, 0xcf, 0x99, 0x7d, 0xe7, 0xe6, 0x9a, 0x32, 0x9d, 0x54,
	0xf0, 0x1d, 0xa0, 0x3a, 0xa3, 0xda, 0x74, 0x4e, 0xd9, 0xd4, 0x58, 0x19, 0x8c, 0xab, 0xcc, 0x71,
	0x89, 0x84, 0x3d, 0xe8, 0xa8, 0x33, 0xc7, 0xd1, 0xb9, 0x67, 0xaf, 0x34, 0xcb, 0x60, 0xa4, 0x8a,
	0x04, 0xda, 0xda, 0x7a, 0x69, 0xeb, 0x9c, 0x39, 0xaa, 0x6a, 0x30, 0xf2, 0x2a, 0x23, 0x2e, 0x6c,
	0xd3, 0x5a, 0xcd, 0x29, 0x33, 0x0a, 0x62, 0x0d, 0x11, 0xba, 0xae, 0x45, 0x75, 0xc7, 0xe3, 0xf4,
	0xa7, 0xb1, 0x30, 0x0d, 0x46, 0xea, 0xf8, 0x1a, 0x6a, 0xae, 0x67, 0xd9, 0xa4, 0x81, 0x00, 0x0d,
	0xd7, 0x33, 0x2d, 0x7b, 0x42, 0x9a, 0xca, 0x0f, 0x20, 0x6e, 0xea, 0xc7, 0x69, 0x16, 0x92, 0x89,
	0xff, 0x47, 0x91, 0xa4, 0xf8, 0x15, 0x3a, 0x81, 0x38, 0xf1, 0xac, 0x0e, 0xbe, 0x0f, 0xb6, 0x61,
	0xfe, 0x37, 0xf2, 0x18, 0x6f, 0x0b, 0x67, 0x72, 0x70, 0x15, 0x8a, 0x0a, 0xbd, 0x12, 0x2b, 0x89,
	0xc2, 0x20, 0x11, 0xf8, 0x19, 0x30, 0x2e, 0xd6, 0x3c, 0xc9, 0xdc, 0x0c, 0x9b, 0x13, 0x5b, 0xac,
	0x77, 0x71, 0xdc, 0x8b, 0x31, 0xf6, 0xa0, 0x9d, 0x8b, 0xe2, 0x11, 0x34, 0x4b, 0xf9, 0x5c, 0x11,
	0xdf, 0xed, 0x7f, 0x0b, 0x7c, 0x5f, 0x04, 0x79, 0x19, 0xfc, 0x63, 0xff, 0xd6, 0x38, 0xf3, 0x95,
	0x8a, 0xda, 0xfa, 0xd5, 0x2c, 0xba, 0x63, 0xd3, 0xc8, 0x1b, 0x63, 0xf2, 0x14, 0x00, 0x00, 0xff,
	0xff, 0xb9, 0xff, 0x6e, 0x1c, 0x35, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StartNewGameClient is the client API for StartNewGame service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StartNewGameClient interface {
	// Unary 开始游戏
	StartGameService(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*StartGameResponse, error)
}

type startNewGameClient struct {
	cc grpc.ClientConnInterface
}

func NewStartNewGameClient(cc grpc.ClientConnInterface) StartNewGameClient {
	return &startNewGameClient{cc}
}

func (c *startNewGameClient) StartGameService(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*StartGameResponse, error) {
	out := new(StartGameResponse)
	err := c.cc.Invoke(ctx, "/judge.StartNewGame/StartGameService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StartNewGameServer is the server API for StartNewGame service.
type StartNewGameServer interface {
	// Unary 开始游戏
	StartGameService(context.Context, *StartGameRequest) (*StartGameResponse, error)
}

// UnimplementedStartNewGameServer can be embedded to have forward compatible implementations.
type UnimplementedStartNewGameServer struct {
}

func (*UnimplementedStartNewGameServer) StartGameService(ctx context.Context, req *StartGameRequest) (*StartGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartGameService not implemented")
}

func RegisterStartNewGameServer(s *grpc.Server, srv StartNewGameServer) {
	s.RegisterService(&_StartNewGame_serviceDesc, srv)
}

func _StartNewGame_StartGameService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StartNewGameServer).StartGameService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/judge.StartNewGame/StartGameService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StartNewGameServer).StartGameService(ctx, req.(*StartGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StartNewGame_serviceDesc = grpc.ServiceDesc{
	ServiceName: "judge.StartNewGame",
	HandlerType: (*StartNewGameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartGameService",
			Handler:    _StartNewGame_StartGameService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "judge/judgepb/judge.proto",
}
