// Code generated by protoc-gen-go. DO NOT EDIT.
// source: judge/judgepb/judge.proto

package judgepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GamePattern int32

const (
	GamePattern_CHARMWOLF_GUARD    GamePattern = 0
	GamePattern_BLACKMARKETER_BROS GamePattern = 1
	GamePattern_BLOOD_WITCHER      GamePattern = 2
	GamePattern_CUPID_ROBBER       GamePattern = 3
	GamePattern_NIGHTMARE_GUARD    GamePattern = 4
	GamePattern_SHADOW_AVENGER     GamePattern = 5
	GamePattern_SWHI               GamePattern = 6
	GamePattern_SWGHI3             GamePattern = 7
)

var GamePattern_name = map[int32]string{
	0: "CHARMWOLF_GUARD",
	1: "BLACKMARKETER_BROS",
	2: "BLOOD_WITCHER",
	3: "CUPID_ROBBER",
	4: "NIGHTMARE_GUARD",
	5: "SHADOW_AVENGER",
	6: "SWHI",
	7: "SWGHI3",
}

var GamePattern_value = map[string]int32{
	"CHARMWOLF_GUARD":    0,
	"BLACKMARKETER_BROS": 1,
	"BLOOD_WITCHER":      2,
	"CUPID_ROBBER":       3,
	"NIGHTMARE_GUARD":    4,
	"SHADOW_AVENGER":     5,
	"SWHI":               6,
	"SWGHI3":             7,
}

func (x GamePattern) String() string {
	return proto.EnumName(GamePattern_name, int32(x))
}

func (GamePattern) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d265219a8a7b46e8, []int{0}
}

type Password struct {
	Num1                 int32    `protobuf:"varint,1,opt,name=num1,proto3" json:"num1,omitempty"`
	Num2                 int32    `protobuf:"varint,2,opt,name=num2,proto3" json:"num2,omitempty"`
	Num3                 int32    `protobuf:"varint,3,opt,name=num3,proto3" json:"num3,omitempty"`
	Num4                 int32    `protobuf:"varint,4,opt,name=num4,proto3" json:"num4,omitempty"`
	Num5                 int32    `protobuf:"varint,5,opt,name=num5,proto3" json:"num5,omitempty"`
	Num6                 int32    `protobuf:"varint,6,opt,name=num6,proto3" json:"num6,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Password) Reset()         { *m = Password{} }
func (m *Password) String() string { return proto.CompactTextString(m) }
func (*Password) ProtoMessage()    {}
func (*Password) Descriptor() ([]byte, []int) {
	return fileDescriptor_d265219a8a7b46e8, []int{0}
}

func (m *Password) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Password.Unmarshal(m, b)
}
func (m *Password) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Password.Marshal(b, m, deterministic)
}
func (m *Password) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Password.Merge(m, src)
}
func (m *Password) XXX_Size() int {
	return xxx_messageInfo_Password.Size(m)
}
func (m *Password) XXX_DiscardUnknown() {
	xxx_messageInfo_Password.DiscardUnknown(m)
}

var xxx_messageInfo_Password proto.InternalMessageInfo

func (m *Password) GetNum1() int32 {
	if m != nil {
		return m.Num1
	}
	return 0
}

func (m *Password) GetNum2() int32 {
	if m != nil {
		return m.Num2
	}
	return 0
}

func (m *Password) GetNum3() int32 {
	if m != nil {
		return m.Num3
	}
	return 0
}

func (m *Password) GetNum4() int32 {
	if m != nil {
		return m.Num4
	}
	return 0
}

func (m *Password) GetNum5() int32 {
	if m != nil {
		return m.Num5
	}
	return 0
}

func (m *Password) GetNum6() int32 {
	if m != nil {
		return m.Num6
	}
	return 0
}

type NewGameInfo struct {
	PlayerAmount         int32       `protobuf:"varint,1,opt,name=player_amount,json=playerAmount,proto3" json:"player_amount,omitempty"`
	GamePattern          GamePattern `protobuf:"varint,2,opt,name=game_pattern,json=gamePattern,proto3,enum=judge.GamePattern" json:"game_pattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NewGameInfo) Reset()         { *m = NewGameInfo{} }
func (m *NewGameInfo) String() string { return proto.CompactTextString(m) }
func (*NewGameInfo) ProtoMessage()    {}
func (*NewGameInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d265219a8a7b46e8, []int{1}
}

func (m *NewGameInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewGameInfo.Unmarshal(m, b)
}
func (m *NewGameInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewGameInfo.Marshal(b, m, deterministic)
}
func (m *NewGameInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewGameInfo.Merge(m, src)
}
func (m *NewGameInfo) XXX_Size() int {
	return xxx_messageInfo_NewGameInfo.Size(m)
}
func (m *NewGameInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NewGameInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NewGameInfo proto.InternalMessageInfo

func (m *NewGameInfo) GetPlayerAmount() int32 {
	if m != nil {
		return m.PlayerAmount
	}
	return 0
}

func (m *NewGameInfo) GetGamePattern() GamePattern {
	if m != nil {
		return m.GamePattern
	}
	return GamePattern_CHARMWOLF_GUARD
}

type StartGameRequest struct {
	NewGameInfo          *NewGameInfo `protobuf:"bytes,1,opt,name=new_game_info,json=newGameInfo,proto3" json:"new_game_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *StartGameRequest) Reset()         { *m = StartGameRequest{} }
func (m *StartGameRequest) String() string { return proto.CompactTextString(m) }
func (*StartGameRequest) ProtoMessage()    {}
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d265219a8a7b46e8, []int{2}
}

func (m *StartGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartGameRequest.Unmarshal(m, b)
}
func (m *StartGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartGameRequest.Marshal(b, m, deterministic)
}
func (m *StartGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartGameRequest.Merge(m, src)
}
func (m *StartGameRequest) XXX_Size() int {
	return xxx_messageInfo_StartGameRequest.Size(m)
}
func (m *StartGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartGameRequest proto.InternalMessageInfo

func (m *StartGameRequest) GetNewGameInfo() *NewGameInfo {
	if m != nil {
		return m.NewGameInfo
	}
	return nil
}

type StartGameResponse struct {
	ResponseStartgame    string      `protobuf:"bytes,1,opt,name=response_startgame,json=responseStartgame,proto3" json:"response_startgame,omitempty"`
	PlayerAmount         int32       `protobuf:"varint,2,opt,name=player_amount,json=playerAmount,proto3" json:"player_amount,omitempty"`
	GamePattern          GamePattern `protobuf:"varint,3,opt,name=gamePattern,proto3,enum=judge.GamePattern" json:"gamePattern,omitempty"`
	NewGamePassword      *Password   `protobuf:"bytes,4,opt,name=new_game_password,json=newGamePassword,proto3" json:"new_game_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StartGameResponse) Reset()         { *m = StartGameResponse{} }
func (m *StartGameResponse) String() string { return proto.CompactTextString(m) }
func (*StartGameResponse) ProtoMessage()    {}
func (*StartGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d265219a8a7b46e8, []int{3}
}

func (m *StartGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartGameResponse.Unmarshal(m, b)
}
func (m *StartGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartGameResponse.Marshal(b, m, deterministic)
}
func (m *StartGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartGameResponse.Merge(m, src)
}
func (m *StartGameResponse) XXX_Size() int {
	return xxx_messageInfo_StartGameResponse.Size(m)
}
func (m *StartGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartGameResponse proto.InternalMessageInfo

func (m *StartGameResponse) GetResponseStartgame() string {
	if m != nil {
		return m.ResponseStartgame
	}
	return ""
}

func (m *StartGameResponse) GetPlayerAmount() int32 {
	if m != nil {
		return m.PlayerAmount
	}
	return 0
}

func (m *StartGameResponse) GetGamePattern() GamePattern {
	if m != nil {
		return m.GamePattern
	}
	return GamePattern_CHARMWOLF_GUARD
}

func (m *StartGameResponse) GetNewGamePassword() *Password {
	if m != nil {
		return m.NewGamePassword
	}
	return nil
}

func init() {
	proto.RegisterEnum("judge.GamePattern", GamePattern_name, GamePattern_value)
	proto.RegisterType((*Password)(nil), "judge.Password")
	proto.RegisterType((*NewGameInfo)(nil), "judge.NewGameInfo")
	proto.RegisterType((*StartGameRequest)(nil), "judge.StartGameRequest")
	proto.RegisterType((*StartGameResponse)(nil), "judge.StartGameResponse")
}

func init() { proto.RegisterFile("judge/judgepb/judge.proto", fileDescriptor_d265219a8a7b46e8) }

var fileDescriptor_d265219a8a7b46e8 = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xdf, 0x8e, 0x93, 0x40,
	0x14, 0xc6, 0x97, 0x6e, 0xdb, 0xdd, 0x3d, 0xb4, 0x5b, 0x7a, 0x4c, 0x14, 0xbd, 0x32, 0x78, 0x63,
	0x4c, 0x5c, 0x23, 0xfd, 0x73, 0xe3, 0x15, 0xb4, 0x08, 0xb8, 0x6d, 0x69, 0x86, 0xae, 0x24, 0xde,
	0x4c, 0x58, 0x77, 0xb6, 0xa9, 0xb1, 0x80, 0x40, 0x6d, 0xbc, 0xf5, 0x41, 0x7c, 0x30, 0x9f, 0xc6,
	0x30, 0x4c, 0x59, 0x62, 0x4d, 0xbc, 0x81, 0x39, 0xbf, 0x03, 0xdf, 0x9c, 0x6f, 0xbe, 0x0c, 0x3c,
	0xfd, 0xb2, 0xbb, 0x5b, 0xb3, 0x37, 0xfc, 0x99, 0xdc, 0x96, 0xef, 0xab, 0x24, 0x8d, 0xf3, 0x18,
	0x5b, 0xbc, 0xd0, 0x7e, 0x4a, 0x70, 0xbe, 0x0c, 0xb3, 0x6c, 0x1f, 0xa7, 0x77, 0x88, 0xd0, 0x8c,
	0x76, 0xdb, 0xb7, 0xaa, 0xf4, 0x5c, 0x7a, 0xd9, 0x22, 0x7c, 0x2d, 0x98, 0xae, 0x36, 0x2a, 0xa6,
	0x0b, 0x36, 0x50, 0x4f, 0x2b, 0x36, 0x10, 0x6c, 0xa8, 0x36, 0x2b, 0x36, 0x14, 0x6c, 0xa4, 0xb6,
	0x2a, 0x36, 0x12, 0x6c, 0xac, 0xb6, 0x2b, 0x36, 0xd6, 0x36, 0x20, 0x2f, 0xd8, 0xde, 0x0e, 0xb7,
	0xcc, 0x8d, 0xee, 0x63, 0x7c, 0x01, 0xdd, 0xe4, 0x6b, 0xf8, 0x83, 0xa5, 0x34, 0xdc, 0xc6, 0xbb,
	0x28, 0x17, 0xf3, 0x74, 0x4a, 0x68, 0x70, 0x86, 0x23, 0xe8, 0xac, 0xc3, 0x2d, 0xa3, 0x49, 0x98,
	0xe7, 0x2c, 0x8d, 0xf8, 0x7c, 0x97, 0x3a, 0x5e, 0x95, 0x1e, 0x0b, 0xad, 0x65, 0xd9, 0x21, 0xf2,
	0xfa, 0xa1, 0xd0, 0x3e, 0x80, 0xe2, 0xe7, 0x61, 0x9a, 0x17, 0x1f, 0x10, 0xf6, 0x6d, 0xc7, 0xb2,
	0x1c, 0xc7, 0xd0, 0x8d, 0xd8, 0x9e, 0x72, 0xb9, 0x4d, 0x74, 0x1f, 0xf3, 0xfd, 0xe4, 0x4a, 0xab,
	0x36, 0x1a, 0x91, 0xa3, 0x87, 0x42, 0xfb, 0x2d, 0x41, 0xbf, 0x26, 0x96, 0x25, 0x71, 0x94, 0x31,
	0x7c, 0x0d, 0x98, 0x8a, 0x35, 0xcd, 0x8a, 0x6e, 0xa1, 0xcb, 0x25, 0x2f, 0x48, 0xff, 0xd0, 0xf1,
	0x0f, 0x8d, 0x63, 0xb3, 0x8d, 0x7f, 0x98, 0x1d, 0x42, 0xdd, 0x04, 0x3f, 0xf7, 0xff, 0x7b, 0xc5,
	0x77, 0xd0, 0xaf, 0x7c, 0x25, 0x22, 0x63, 0x9e, 0x8f, 0xac, 0xf7, 0xc4, 0xbf, 0x87, 0xe8, 0x49,
	0x4f, 0x18, 0x3b, 0x80, 0x57, 0xbf, 0x24, 0x90, 0x6b, 0xca, 0xf8, 0x08, 0x7a, 0x13, 0xc7, 0x20,
	0xf3, 0xc0, 0x9b, 0xbd, 0xa7, 0xf6, 0x8d, 0x41, 0xa6, 0xca, 0x09, 0x3e, 0x06, 0x34, 0x67, 0xc6,
	0xe4, 0x7a, 0x6e, 0x90, 0x6b, 0x6b, 0x65, 0x11, 0x6a, 0x12, 0xcf, 0x57, 0x24, 0xec, 0x43, 0xd7,
	0x9c, 0x79, 0xde, 0x94, 0x06, 0xee, 0x6a, 0xe2, 0x58, 0x44, 0x69, 0xa0, 0x02, 0x9d, 0xc9, 0xcd,
	0xd2, 0x9d, 0x52, 0xe2, 0x99, 0xa6, 0x45, 0x94, 0xd3, 0x42, 0x71, 0xe1, 0xda, 0xce, 0x6a, 0x6e,
	0x10, 0x4b, 0x28, 0x36, 0x11, 0xe1, 0xd2, 0x77, 0x8c, 0xa9, 0x17, 0x50, 0xe3, 0xa3, 0xb5, 0xb0,
	0x2d, 0xa2, 0xb4, 0xf0, 0x1c, 0x9a, 0x7e, 0xe0, 0xb8, 0x4a, 0x1b, 0x01, 0xda, 0x7e, 0x60, 0x3b,
	0xee, 0x40, 0x39, 0xd3, 0x03, 0xe8, 0xf0, 0x53, 0x14, 0xf1, 0xa0, 0x5d, 0x4b, 0xd6, 0x67, 0xe9,
	0xf7, 0xcd, 0x67, 0x86, 0x4f, 0x84, 0xcd, 0xbf, 0x23, 0x7f, 0xa6, 0x1e, 0x37, 0xca, 0x60, 0xb4,
	0x13, 0xf3, 0xe2, 0xd3, 0x99, 0xb8, 0x30, 0xb7, 0x6d, 0x7e, 0x57, 0x06, 0x7f, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x7a, 0xdc, 0x9f, 0x49, 0x48, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StartNewGameClient is the client API for StartNewGame service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StartNewGameClient interface {
	// Unary 开始游戏
	StartGameService(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*StartGameResponse, error)
}

type startNewGameClient struct {
	cc grpc.ClientConnInterface
}

func NewStartNewGameClient(cc grpc.ClientConnInterface) StartNewGameClient {
	return &startNewGameClient{cc}
}

func (c *startNewGameClient) StartGameService(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*StartGameResponse, error) {
	out := new(StartGameResponse)
	err := c.cc.Invoke(ctx, "/judge.StartNewGame/StartGameService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StartNewGameServer is the server API for StartNewGame service.
type StartNewGameServer interface {
	// Unary 开始游戏
	StartGameService(context.Context, *StartGameRequest) (*StartGameResponse, error)
}

// UnimplementedStartNewGameServer can be embedded to have forward compatible implementations.
type UnimplementedStartNewGameServer struct {
}

func (*UnimplementedStartNewGameServer) StartGameService(ctx context.Context, req *StartGameRequest) (*StartGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartGameService not implemented")
}

func RegisterStartNewGameServer(s *grpc.Server, srv StartNewGameServer) {
	s.RegisterService(&_StartNewGame_serviceDesc, srv)
}

func _StartNewGame_StartGameService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StartNewGameServer).StartGameService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/judge.StartNewGame/StartGameService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StartNewGameServer).StartGameService(ctx, req.(*StartGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StartNewGame_serviceDesc = grpc.ServiceDesc{
	ServiceName: "judge.StartNewGame",
	HandlerType: (*StartNewGameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartGameService",
			Handler:    _StartNewGame_StartGameService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "judge/judgepb/judge.proto",
}
